baseURL = "https://docs.avo.la/"
languageCode = "en-us"
title = "Avola Documentation"
theme = "hugo-theme-docdock"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
editURL = "https://github.com/Avola/docs/tree/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/avola"
weight = 10

# [[menu.shortcuts]]
# name = "<i class='fa fa-camera'></i> Showcases"
# url = "/showcase"
# weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-twitter'></i> Twitter"
url = "https://twitter.com/avoladecision"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-external-link-square'></i> Avola Website"
url = "http://www.avo.la"
weight = 30