baseURL = "http://avola-docs.azurewebsites.net/"
languageCode = "en-us"
title = "Avola API Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Avola Decision"
	description = "Documentation for the Avola API"
	copyright = "Released under the MIT license"

	# Repository (adds links in sidebar)
	# provider = "GitHub"
	# repo_url = "https://github.com/avola/avola-client"

	# version = "1.0.0"
	logo = "images/avola-logo-bol.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "avoladecision"
	github  = "avola"
	email   = "mail@avo.la"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "API"
	url    = "api/"
	weight = 10
